services:
  app:
    container_name: nginx
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped #Usar "always" en caso necesario
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
